FROM node:18.7.0-bullseye-slim

ARG USER=${USER}
ARG GROUP=${USER}

RUN useradd $USER \
    && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
    && chmod 0440 /etc/sudoers.d/$USER

RUN usermod -u 1000 $USER && groupmod -g 1000 $USER

USER 1000:1000

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

# RUN chown -R ${USER}:${GROUP} ./node_modules/

RUN yarn add pg

RUN yarn install

COPY . .

EXPOSE 3001

CMD [ "yarn", "start:dev"]