FROM node:19.4.0-buster-slim

RUN apt-get update -y && apt-get install openssl -y && apt-get install nano
WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

ARG DATABASE_URL

RUN yarn install

COPY . .

RUN yarn generate

EXPOSE 3001

CMD [ "yarn", "start:dev"]
