FROM node:18.9.1-buster-slim

RUN apt-get update -y && apt-get install openssl -y
WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

ARG DATABASE_URL

RUN yarn install

COPY . .

RUN yarn generate

EXPOSE 3001

CMD [ "yarn", "start:dev"]