FROM node:18.7.0-bullseye-slim

ARG ENV_MODE=production
ENV NODE_ENV=${ENV_MODE}

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

RUN yarn install --only-production

COPY . .

RUN yarn build && yarn prune --production

CMD ["node", "dist/main"]
